para_root: "~"

buckets:
  projects: 1_Projects
  areas: 2_Areas
  resources: 3_Resources
  archive: 4_Archive

rules:
  - name: Images
    ext: [png, jpg, jpeg, gif, webp]
    bucket: resources
    path: Images

  - name: Archives
    ext: [zip, rar, 7z, tar, gz]
    bucket: archive
    path: archives

  - name: PDFs
    ext: [pdf]
    bucket: resources
    path: PDFs
